http:
  routers:
    # Router para autenticación
    auth-router:
      rule: "PathPrefix(`/autenticacion`)"
      service: auth-service
      entryPoints:
        - web
      middlewares:
        - cors-middleware

    # Router para frontend
    frontend-router:
      rule: "PathPrefix(`/index`)"
      service: frontend-service
      entryPoints:
        - web
      middlewares:
        - cors-middleware

    # Router para pedidos
    pedido-router:
      rule: "PathPrefix(`/pedido`) || PathPrefix(`/registro`)"
      service: pedido-service
      entryPoints:
        - web
      middlewares:
        - cors-middleware

    # Router para el dashboard de Traefik
    dashboard-router:
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      service: api@internal
      entryPoints:
        - web

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://authentication-service:8081"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend-service:8080"

    pedido-service:
      loadBalancer:
        servers:
          - url: "http://pedido-service:8083"

  middlewares:
    cors-middleware:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100